# Generated by Django 3.0 on 2020-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMan',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
    ]
